### ISSUE TITLE
No member named 'getSize' in 'juce::Rectangle<int>'

### ISSUE THREAD

**Issue by adamski** [cognitone/UIModelFramework#1]
https://github.com/cognitone/UIModelFramework/blob/d1ec9f63a735e02b9c9b5c58a6fdd5dad0a84a8e/Source/UI/utility/LayoutCursor.cpp#L39

Not sure if this has entered JUCE in recent commits, I couldn't find it anywhere... did you use a modified version of juce::Rectangle with a `getSize` method?

**Comment by adamski** [comment]
I think this should be 
```
auto extent = comp->getBounds().getBottomRight() + Point<int>(4, 2);
```

**Comment by adamski** [comment]
I just saw the discussion here: https://forum.juce.com/t/rectangle-getsize-missing/32328/14
I see your point, but until that is part of the JUCE library let's use what's available there now..

**Comment by aurelium** [comment]
Sorry, removing this before publishing slipped my attention. Replaced it with this:
```
    auto bounds = comp->getBounds();
    auto extent = Point<int>(bounds.getWidth(), bounds.getHeight()) + Point<int>(4, 2);
```
This extra hoop was exactly the motivation to request something like getSize() or getExtent() as a Juce feature.
